### PR TITLE
mavenize module

### PR DESCRIPTION
**Pull request by antonioalf**
mavenize module

### CODE REVIEW

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP.

**Comment by witokondoria** [comment]
:shi

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP.

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP.

**Pull request merged**
